name: dama
description: DArt MAth package.
version: 2.0.2
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  logging: ^1.0.0
  more: ^3.0.1
  table:
    git: https://github.com/thumbert/table.git
  tuple: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5
