name: dama
description: DArt MAth package.
version: 2.0.2
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  logging: ^1.0.0
  more: ^4.0.1
  table:
    git: https://github.com/thumbert/table.git
  tuple: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.5
