name: dama
description: DArt MAth package.
version: 2.0.1
author: Tony Humbert <tony.humberts@gmail.com>
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  logging: ^1.0.0
  more: ^3.0.1
  table:
    git:
      url: git://github.com/thumbert/table.git

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
