name: dama
description: DArt MAth package.
version: 1.1.1
author: <Tony Humbert> <tony.humberts@gmail.com>
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  logging: '>=0.11.3 <1.0.0'
  more: '>=1.12.0 <2.0.0'
  table:
    git:
      url: git://github.com/thumbert/table.git
      ref: non-null

dev_dependencies:
  pedantic: ^1.9.0
  test: '>=1.0.0 <2.0.0'
