name: dama
description: DArt MAth package.
version: 1.0.0
author: <Tony Humbert> <tony.humberts@gmail.com>
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  logging: '>=0.11.3 <1.0.0'
  more: '>=1.12.0 <2.0.0'

dev_dependencies:
  test: '>=1.0.0 <2.0.0'
