name: dama
description: DArt MAth package.
version: 2.0.2
publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  more: ^3.10.2
  table:
    git: https://github.com/thumbert/table.git
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  logging: ^1.0.0
  test: ^1.16.5
